# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'cms_news_news_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='newstranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms_news.News'),
        ),
        migrations.AlterUniqueTogether(
            name='newstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
