# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_news', '0002_auto_20160918_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstranslation',
            old_name='text',
            new_name='body',
        ),
    ]
