# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms_news', '0003_auto_20160923_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 9, 23, 19, 58, 10, 395979, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newstranslation',
            name='title',
            field=models.CharField(default='Hello cmz', max_length=300),
            preserve_default=False,
        ),
    ]
