# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_news', '0004_auto_20160923_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslation',
            name='body',
        ),
    ]
