# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seooverride',
            name='page',
            field=models.CharField(choices=[(b'test-your-site', b'test-your-site'), (b'article', b'article'), (b'home', b'home'), (b'technology', b'technology'), (b'projects', b'projects'), (b'web', b'web'), (b'cookie-policy', b'cookie-policy'), (b'apps', b'apps'), (b'terms-and-condition', b'terms-and-condition'), (b'blog', b'blog'), (b'project', b'project'), (b'contact', b'contact'), (b'copyright-notice', b'copyright-notice')], max_length=255),
        ),
    ]
