# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_seo', '0004_auto_20161023_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seooverride',
            name='page',
            field=models.CharField(blank=True, choices=[(b'apps', b'apps'), (b'article', b'article'), (b'blog', b'blog'), (b'contact', b'contact'), (b'cookie-policy', b'cookie-policy'), (b'copyright-notice', b'copyright-notice'), (b'home', b'home'), (b'project', b'project'), (b'projects', b'projects'), (b'technology', b'technology'), (b'terms-and-condition', b'terms-and-condition'), (b'test-your-site', b'test-your-site'), (b'web', b'web')], max_length=255, null=True),
        ),
    ]
